# SPDX-License-Identifier: Apache-2.0

[package]
name = "novaire-yt-token"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk.workspace = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
novaire-sy-wrapper = { path = "../sy-wrapper" }
novaire-tokenizer = { path = "../tokenizer" }
novaire-blend-adapter = { path = "../blend-adapter", features = ["testutils"] }
