# SPDX-License-Identifier: Apache-2.0

[package]
name = "novaire-amm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
novaire-shared-types = { path = "../shared/types" }
soroban-sdk.workspace = true

[dev-dependencies]
proptest = "1.9.0"
novaire-sy-wrapper = { path = "../sy-wrapper" }
novaire-blend-adapter = { path = "../blend-adapter", features = ["testutils"] }
soroban-sdk = { workspace = true, features = ["testutils"] }
