[package]
name = "tokenizer"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "27.0.5"

[dev-dependencies]
soroban-sdk = { version = "27.0.5", features = ["testutils"] }
vault = { path = "../../vault" }
sy_wrapper = { path = "../../sy_wrapper" }
pt_token = { path = "../pt_token" }
yt_token = { path = "../yt_token" }
maturity_engine = { path = "../../maturity_engine" }
